# Generated by Django 4.2.8 on 2025-12-24 06:43

from django.db import migrations


def convert_managers_to_employees(apps, schema_editor):
    """Convert all MANAGER roles to EMPLOYEE"""
    User = apps.get_model('users', 'User')
    # Update all MANAGER users to EMPLOYEE
    updated_count = User.objects.filter(role='MANAGER').update(role='EMPLOYEE')
    if updated_count > 0:
        print(f"Converted {updated_count} MANAGER user(s) to EMPLOYEE")


def reverse_migration(apps, schema_editor):
    """Reverse is not supported - all users remain as EMPLOYEE"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_managers_to_employees, reverse_migration),
    ]
