# Generated by Django 4.2.8 on 2025-12-24 06:47

from django.db import migrations


def convert_user_role_to_employee(apps, schema_editor):
    """Convert all USER roles to EMPLOYEE"""
    User = apps.get_model('users', 'User')
    # Update all USER users to EMPLOYEE
    updated_count = User.objects.filter(role='USER').update(role='EMPLOYEE')
    if updated_count > 0:
        print(f"Converted {updated_count} USER role(s) to EMPLOYEE")


def reverse_migration(apps, schema_editor):
    """Reverse is not supported - all users remain as EMPLOYEE"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_convert_managers_to_employees'),
    ]

    operations = [
        migrations.RunPython(convert_user_role_to_employee, reverse_migration),
    ]
