# Generated by Django 4.2.8 on 2025-12-22

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0002_initial'),
        ('projects', '0002_initial'),
        ('departments', '0002_initial'),
        ('audit', '0002_initial'),
    ]

    operations = [
        # Stored Procedure 1: Get Employee Timesheet Summary
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_get_employee_timesheet_summary(
                IN emp_id INT,
                IN start_date DATE,
                IN end_date DATE
            )
            BEGIN
                SELECT 
                    u.id AS employee_id,
                    CONCAT(u.first_name, ' ', u.last_name) AS employee_name,
                    u.email,
                    d.name AS department_name,
                    COUNT(t.id) AS total_timesheets,
                    SUM(t.hours) AS total_hours,
                    SUM(CASE WHEN t.status = 'APPROVED' THEN t.hours ELSE 0 END) AS approved_hours,
                    SUM(CASE WHEN t.status = 'PENDING' THEN t.hours ELSE 0 END) AS pending_hours,
                    SUM(CASE WHEN t.status = 'REJECTED' THEN t.hours ELSE 0 END) AS rejected_hours
                FROM users_user u
                LEFT JOIN departments_department d ON u.department_id = d.id
                LEFT JOIN timesheets_timesheet t ON t.employee_id = u.id
                WHERE u.id = emp_id
                    AND (start_date IS NULL OR t.date >= start_date)
                    AND (end_date IS NULL OR t.date <= end_date)
                GROUP BY u.id, u.first_name, u.last_name, u.email, d.name;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_get_employee_timesheet_summary;"
        ),

        # Stored Procedure 2: Get Project Budget Status
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_get_project_budget_status(
                IN proj_id INT
            )
            BEGIN
                SELECT 
                    p.id AS project_id,
                    p.name AS project_name,
                    p.code AS project_code,
                    p.budget,
                    p.status,
                    COUNT(DISTINCT t.id) AS total_tasks,
                    COUNT(DISTINCT ts.id) AS total_timesheets,
                    COALESCE(SUM(ts.hours), 0) AS total_hours_logged,
                    COALESCE(SUM(ts.hours * 50), 0) AS estimated_cost,
                    (p.budget - COALESCE(SUM(ts.hours * 50), 0)) AS remaining_budget,
                    ROUND(((COALESCE(SUM(ts.hours * 50), 0) / p.budget) * 100), 2) AS budget_utilized_percentage
                FROM projects_project p
                LEFT JOIN tasks_task t ON t.project_id = p.id
                LEFT JOIN timesheets_timesheet ts ON ts.task_id = t.id AND ts.status = 'APPROVED'
                WHERE p.id = proj_id
                GROUP BY p.id, p.name, p.code, p.budget, p.status;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_get_project_budget_status;"
        ),

        # Stored Procedure 3: Get Department Performance Metrics
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_get_department_performance(
                IN dept_id INT,
                IN report_month INT,
                IN report_year INT
            )
            BEGIN
                SELECT 
                    d.id AS department_id,
                    d.name AS department_name,
                    d.code AS department_code,
                    COUNT(DISTINCT u.id) AS total_employees,
                    COUNT(DISTINCT p.id) AS total_projects,
                    COUNT(DISTINCT t.id) AS total_tasks,
                    COUNT(DISTINCT ts.id) AS total_timesheets,
                    COALESCE(SUM(ts.hours), 0) AS total_hours_worked,
                    COALESCE(AVG(ts.hours), 0) AS avg_hours_per_timesheet,
                    COUNT(DISTINCT CASE WHEN t.status = 'COMPLETED' THEN t.id END) AS completed_tasks,
                    COUNT(DISTINCT CASE WHEN t.status = 'IN_PROGRESS' THEN t.id END) AS in_progress_tasks,
                    ROUND((COUNT(DISTINCT CASE WHEN t.status = 'COMPLETED' THEN t.id END) / 
                           NULLIF(COUNT(DISTINCT t.id), 0) * 100), 2) AS task_completion_rate
                FROM departments_department d
                LEFT JOIN users_user u ON u.department_id = d.id AND u.is_active = 1
                LEFT JOIN projects_project p ON p.department_id = d.id
                LEFT JOIN tasks_task t ON t.project_id = p.id
                LEFT JOIN timesheets_timesheet ts ON ts.employee_id = u.id
                    AND MONTH(ts.date) = report_month
                    AND YEAR(ts.date) = report_year
                WHERE d.id = dept_id
                GROUP BY d.id, d.name, d.code;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_get_department_performance;"
        ),

        # Stored Procedure 4: Bulk Approve Timesheets
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_bulk_approve_timesheets(
                IN approver_id INT,
                IN timesheet_ids TEXT
            )
            BEGIN
                DECLARE affected_rows INT DEFAULT 0;
                
                UPDATE timesheets_timesheet
                SET 
                    status = 'APPROVED',
                    approved_by_id = approver_id,
                    approved_at = NOW(),
                    updated_at = NOW()
                WHERE FIND_IN_SET(id, timesheet_ids) > 0
                    AND status = 'PENDING';
                
                SET affected_rows = ROW_COUNT();
                
                SELECT 
                    affected_rows AS timesheets_approved,
                    'Success' AS status,
                    NOW() AS approved_at;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_bulk_approve_timesheets;"
        ),

        # Stored Procedure 5: Get Audit Trail for Entity
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_get_audit_trail(
                IN entity_type VARCHAR(50),
                IN entity_id INT,
                IN limit_records INT
            )
            BEGIN
                SELECT 
                    a.id,
                    a.action,
                    a.model_name,
                    a.object_id,
                    a.changes,
                    a.ip_address,
                    a.user_agent,
                    a.timestamp,
                    CONCAT(u.first_name, ' ', u.last_name) AS user_name,
                    u.email AS user_email,
                    u.role AS user_role
                FROM audit_auditlog a
                LEFT JOIN users_user u ON a.user_id = u.id
                WHERE a.model_name = entity_type
                    AND (entity_id IS NULL OR a.object_id = entity_id)
                ORDER BY a.timestamp DESC
                LIMIT limit_records;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_get_audit_trail;"
        ),

        # Stored Procedure 6: Get Task Productivity Report
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_get_task_productivity_report(
                IN start_date DATE,
                IN end_date DATE
            )
            BEGIN
                SELECT 
                    t.id AS task_id,
                    t.title AS task_title,
                    t.priority,
                    t.status,
                    p.name AS project_name,
                    CONCAT(assigned.first_name, ' ', assigned.last_name) AS assigned_to,
                    COUNT(ts.id) AS total_timesheet_entries,
                    COALESCE(SUM(ts.hours), 0) AS total_hours_spent,
                    t.estimated_hours,
                    (t.estimated_hours - COALESCE(SUM(ts.hours), 0)) AS hours_variance,
                    CASE 
                        WHEN t.estimated_hours > 0 THEN 
                            ROUND((COALESCE(SUM(ts.hours), 0) / t.estimated_hours * 100), 2)
                        ELSE 0 
                    END AS time_utilization_percentage,
                    DATEDIFF(COALESCE(t.completed_at, NOW()), t.created_at) AS days_in_progress
                FROM tasks_task t
                LEFT JOIN projects_project p ON t.project_id = p.id
                LEFT JOIN users_user assigned ON t.assigned_to_id = assigned.id
                LEFT JOIN timesheets_timesheet ts ON ts.task_id = t.id 
                    AND ts.date BETWEEN start_date AND end_date
                    AND ts.status = 'APPROVED'
                GROUP BY t.id, t.title, t.priority, t.status, p.name, 
                         assigned.first_name, assigned.last_name, 
                         t.estimated_hours, t.created_at, t.completed_at
                ORDER BY total_hours_spent DESC;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_get_task_productivity_report;"
        ),

        # Stored Function 1: Calculate Project Progress
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION fn_calculate_project_progress(proj_id INT)
            RETURNS DECIMAL(5,2)
            DETERMINISTIC
            READS SQL DATA
            BEGIN
                DECLARE total_tasks INT DEFAULT 0;
                DECLARE completed_tasks INT DEFAULT 0;
                DECLARE progress_percentage DECIMAL(5,2) DEFAULT 0.00;
                
                SELECT 
                    COUNT(*),
                    COUNT(CASE WHEN status = 'COMPLETED' THEN 1 END)
                INTO total_tasks, completed_tasks
                FROM tasks_task
                WHERE project_id = proj_id;
                
                IF total_tasks > 0 THEN
                    SET progress_percentage = (completed_tasks / total_tasks) * 100;
                END IF;
                
                RETURN progress_percentage;
            END;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS fn_calculate_project_progress;"
        ),

        # Stored Function 2: Get Employee Utilization Rate
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION fn_get_employee_utilization(emp_id INT, target_month INT, target_year INT)
            RETURNS DECIMAL(5,2)
            DETERMINISTIC
            READS SQL DATA
            BEGIN
                DECLARE total_hours DECIMAL(10,2) DEFAULT 0.00;
                DECLARE working_days INT DEFAULT 22;
                DECLARE standard_hours_per_day DECIMAL(5,2) DEFAULT 8.00;
                DECLARE expected_hours DECIMAL(10,2);
                DECLARE utilization_rate DECIMAL(5,2) DEFAULT 0.00;
                
                SELECT COALESCE(SUM(hours), 0)
                INTO total_hours
                FROM timesheets_timesheet
                WHERE employee_id = emp_id
                    AND MONTH(date) = target_month
                    AND YEAR(date) = target_year
                    AND status = 'APPROVED';
                
                SET expected_hours = working_days * standard_hours_per_day;
                
                IF expected_hours > 0 THEN
                    SET utilization_rate = (total_hours / expected_hours) * 100;
                END IF;
                
                RETURN utilization_rate;
            END;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS fn_get_employee_utilization;"
        ),
    ]
