# Generated by Django 4.2.8 on 2025-12-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
